language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r dev_requirements.txt"
  - "npm install -g grunt-cli"
  - "npm install"
# command to run tests
script:
    - py.test
    - grunt
